[project]
name = "spider"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.11.16",
    "lxml>=5.3.2",
    "pydantic>=2.11.3",
    "pydantic-settings>=2.8.1",
    "requests>=2.32.3",
]
